# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-19 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houduan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shu', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('num', models.IntegerField()),
                ('span', models.CharField(max_length=255)),
                ('p', models.CharField(max_length=255)),
            ],
        ),
    ]
