# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-19 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houduan', '0002_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('isselect', models.BooleanField(default=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houduan.Picture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houduan.UserM')),
            ],
        ),
    ]
